version: 2.1
references:
  nvm_env: &nvm_env
    environment:
      BASH_ENV: '~/.nvm/nvm.sh'
  tag_filter: &tag_filter
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v\d+\.\d+\.\d+$/
commands:
  install-node:
    steps:
      - run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
      - run:
          command: nvm install node
          <<: *nvm_env
jobs:
  build-and-lint:
    docker:
      - image: amazonlinux
    steps:
      - run: yum -y install git tar gzip make gcc-c++
      - install-node
      - checkout
      - run:
          command: npm install
          <<: *nvm_env
      - run:
          command: npm run build
          <<: *nvm_env
      - run:
          command: npm run lint
          <<: *nvm_env
      - persist_to_workspace:
          root: .
          paths:
            - .
  publish:
    docker:
      - image: amazonlinux
    steps:
      - run: yum -y install tar gzip
      - install-node
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
          <<: *nvm_env
      - run:
          name: Publish package
          command: npm publish --unsafe-perm
          <<: *nvm_env
workflows:
  build-and-lint:
    jobs:
      - build-and-lint
  publish:
    jobs:
      - build-and-lint:
          <<: *tag_filter
      - publish:
          requires:
            - build-and-lint
          <<: *tag_filter
